### ISSUE TITLE
Mvn compiled jar cast an error when executing the examples

### ISSUE THREAD

**Issue by paulakeen** [RMLio/RMLStreamer#22]
With the compiled jar, following exactly the instructions in the README.md file, i copied the example files in the directory containing the jar, and when executing either of these two lines it fails:

flink run -c io.rml.framework.Main ./RMLStreamer-2.0.1-SNAPSHOT.jar toFile --mapping-file ./mapping.ttl --output-path ./myoutput.nq

flink run ./RMLStreamer-2.0.1-SNAPSHOT.jar toFile --mapping-file ./mapping.ttl --output-path ./myoutput.nq

In both cases I get this exception:

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: java.util.concurrent.ExecutionException: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:302)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:149)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:699)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:232)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:916)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:992)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)

...
etc.

**Comment by ghsnd** [comment]
Dear @paulakeen ,

Apologies for the late answer!
The exception gives not enough info to see what's going wrong here. Could you also provide Flink's logs, typically found in `<Flink root dir>/logs`?

Best regards,
Gerald
