### ISSUE TITLE
Error parsing the GTFS-Madrid-Bench mapping

### ISSUE THREAD

**Issue by dachafra** [RMLio/RMLStreamer#25]
Hi!
We are trying to execute the RMLStreamer with the mappings and data from the GTFS-Madrid-Benchmark and we are obtaining an error through the parsing of the RML mapping. The mapping and data run perfectly in the RMLMapper or the SDM-RDFizer. (See in the attachment a zip containing the mapping and input CSV files scale 1).

```
at io.rml.framework.core.extractors.std.StdPredicateObjectMapExtractor$$anonfun$extract$1.apply(StdPredicateObjectMapExtractor.scala:64)
	at io.rml.framework.core.extractors.std.StdPredicateObjectMapExtractor$$anonfun$extract$1.apply(StdPredicateObjectMapExtractor.scala:59)
	at scala.collection.immutable.List.map(List.scala:288)
	at io.rml.framework.core.extractors.std.StdPredicateObjectMapExtractor.extract(StdPredicateObjectMapExtractor.scala:59)
	at io.rml.framework.core.extractors.std.StdPredicateObjectMapExtractor.extract(StdPredicateObjectMapExtractor.scala:38)
	at io.rml.framework.core.extractors.std.StdTriplesMapExtractor.extractTriplesMapProperties(StdTriplesMapExtractor.scala:95)
	at io.rml.framework.core.extractors.std.StdObjectMapExtractor.extractParentTriplesMap(StdObjectMapExtractor.scala:181)
	at io.rml.framework.core.extractors.std.StdObjectMapExtractor.io$rml$framework$core$extractors$std$StdObjectMapExtractor$$extractObjectMap(StdObjectMapExtractor.scala:101)
	at io.rml.framework.core.extractors.std.StdObjectMapExtractor$$anonfun$extractObjectMaps$1.apply(StdObjectMapExtractor.scala:81)
	at io.rml.framework.core.extractors.std.StdObjectMapExtractor$$anonfun$extractObjectMaps$1.apply(StdObjectMapExtractor.scala:76)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at io.rml.framework.core.extractors.std.StdObjectMapExtractor.extractObjectMaps(StdObjectMapExtractor.scala:76)
	at io.rml.framework.core.extractors.std.StdObjectMapExtractor.extract(StdObjectMapExtractor.scala:43)
	at io.rml.framework.core.extractors.std.StdObjectMapExtractor.extract(StdObjectMapExtractor.scala:35)
	at io.rml.framework.core.extractors.std.StdPredicateObjectMapExtractor.io$rml$framework$core$extractors$std$StdPredicateObjectMapExtractor$$extractPredicateObjectMap(StdPredicateObjectMapExtractor.scala:76)
	at io.rml.framework.core.extractors.std.StdPredicateObjectMapExtractor$$anonfun$extract$1.apply(StdPredicateObjectMapExtractor.scala:64)
	at io.rml.framework.core.extractors.std.StdPredicateObjectMapExtractor$$anonfun$extract$1.apply(StdPredicateObjectMapExtractor.scala:59)
	at scala.collection.immutable.List.map(List.scala:288)
	at io.rml.framework.core.extractors.std.StdPredicateObjectMapExtractor.extract(StdPredicateObjectMapExtractor.scala:59)
	at io.rml.framework.core.extractors.std.StdPredicateObjectMapExtractor.extract(StdPredicateObjectMapExtractor.scala:38)
	at io.rml.framework.core.extractors.std.StdTriplesMapExtractor.extractTriplesMapProperties(StdTriplesMapExtractor.scala:95)
	at io.rml.framework.core.extractors.std.StdObjectMapExtractor.extractParentTriplesMap(StdObjectMapExtractor.scala:181)
```

[gtfs-data.zip](https://github.com/RMLio/RMLStreamer/files/6067019/gtfs-data.zip)

**Comment by ghsnd** [comment]
Hi David,
Thanks for reporting this. I'll have a look and come back to you.

**Comment by ghsnd** [comment]
Hi @dachafra ,
The error you posted should be fixed on the `development` branch, but is not released yet (related to #19 ). If you want to test, you can build from source or I can provide a jar file. I tried it with parameters `toFile --mapping-file path/to/mapping-gtfs.rml.ttl --output-path /tmp/output` and that seems to work. Let me know if you need more help.
Best regards, Gerald

**Comment by dachafra** [comment]
Could you send me the jar please? here or by email to dachafra@gmail.com, it will be awesome! thank you very much

**Comment by ghsnd** [comment]
[Here](https://cloud.ilabt.imec.be/index.php/s/7MqTCzidAzAQtgY) it is. Good luck!

**Comment by ghsnd** [comment]
Mind that you need Flink 1.11.3 for it to run properly.

**Comment by dachafra** [comment]
1.11.3 or 1.11.2? I saw in the documentation that the version needed is 1.11.2

**Comment by dachafra** [comment]
forget it, it seems that I don't know how to read properly, thanks!

**Comment by dachafra** [comment]
solved!
