### ISSUE TITLE
Web interface submission error

### ISSUE THREAD

**Issue by SemanticInteroperability** [RMLio/RMLStreamer#42]
stay http://localhost:8081/#/submit Interface, I fill in _tofile --mapping-file /mnt/data/scenario-1/mapping.rml. ttl --output-path /mnt/data/scenario-1/output.nt  in  _program arguments_ .According to your steps。 But it reported an error
org.apache.flink.runtime.rest.handler.RestHandlerException: Could not execute application. at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$1(JarRunHandler.java:110) at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source) Caused by: java.util.concurrent.CompletionException: org.apache.flink.util.FlinkRuntimeException: Could not execute application. at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ... 2 more Caused by: org.apache.flink.util.FlinkRuntimeException: Could not execute application. at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:88) at org.apache.flink.client.deployment.application.DetachedApplicationRunner.run(DetachedApplicationRunner.java:70) at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$0(JarRunHandler.java:104) ... 2 more Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: None.get at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) at org.apache.flink.client.deployment.application.DetachedApplicationRunner.tryExecuteJobs(DetachedApplicationRunner.java:84) ... 4 more Caused by: java.util.NoSuchElementException: None.get at scala.None$.get(Option.scala:347) at scala.None$.get(Option.scala:345) at io.rml.framework.Main$.main(Main.scala:102) at io.rml.framework.Main.main(Main.scala) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.base/java.lang.reflect.Method.invoke(Unknown Source) at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ... 7 more

Can you help me out? Looking forward to your reply!

**Comment by ghsnd** [comment]
Hi! This was a bug that has been fixed, but not released yet. 

The best option to overcome this is to build RMLStreamer from the `development` branch, where it is fixed.

If not possible, a workaround is to add the `-f` parameter and an empty file as argument (e.g. `-f /tmp/empty.txt`) OR have it pointing to the descriptions of internal functions (like so: `-f https://raw.githubusercontent.com/FnOio/idlab-functions-java/v0.1.0/src/main/resources/fno/functions_idlab.ttl,https://raw.githubusercontent.com/FnOio/idlab-functions-java/v0.1.0/src/main/resources/fno/functions_idlab_classes_java_mapping.ttl`)

Hope this helps!
