### ISSUE TITLE
Issues: DataSource, KryoSerializer, and "Error in task code:  CHAIN Join (Join child and parent.)".

### ISSUE THREAD

**Issue by PRAE399** [RMLio/RMLStreamer#44]
Hi,

I am trying to run RMLStreamer on an RML file with mapping rules for nine large TSV files (ranging from 1MB to 2GB).
I am running the following command: 
`java -jar RMLStreamer-2.4.2-standalone.jar toFile -m /C:\Users\patri\Desktop\RML\RML_test\test_Files_M_PSWM_IL.ttl -o /C:/Users/patri/Desktop/RML/RML_test/Outputs/testFilesRDF_M_PSWM_IL`.
I have been having some issues while doing this and therefore ask for some guidance in solving them:
1) When I have an output, the files do not have an extension.
2) The output folder always has 8 files (or 16 if I run in a server) , no matter how many TSV files are mapped in the RML file. I feel like I'm losing data.
3) When running, there is usually a neverending stream of errors, some of which appear as follows:

- `12:14:12,332 WARN  io.rml.framework.core.item.csv.CSVItem$                       - Cannot find reference: 'GRCH38-HG38-ENSEMBLv94'. Continuing with no value for this reference.` (this, I believe, is on my end. I was trying to have a constant TriplesMap that is not in any file, but was related to others, but have not found a way of doing so in the correct way);

- `12:15:02,916 WARN  org.apache.flink.metrics.MetricGroup                          - The operator name DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.createInput(ExecutionEnvironment.scala:360) (io.rml.framework.flink.source.CSVInputFormat)) exceeded the 80 characters length limit and was truncated.`;

- `12:15:03,512 WARN  org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer  - Falling back to default Kryo serializer because Chill serializer couldn't be found.
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.getKryoInstance(KryoSerializer.java:444)
        at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.checkKryoInitialized(KryoSerializer.java:467)        at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:299)
        at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.serialize(TupleSerializer.java:140)
        at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.serialize(TupleSerializer.java:37)
        at org.apache.flink.runtime.plugable.SerializationDelegate.write(SerializationDelegate.java:54)
        at org.apache.flink.runtime.io.network.api.writer.RecordWriter.serializeRecord(RecordWriter.java:132)
        at org.apache.flink.runtime.io.network.api.writer.RecordWriter.emit(RecordWriter.java:106)
        at org.apache.flink.runtime.io.network.api.writer.ChannelSelectorRecordWriter.emit(ChannelSelectorRecordWriter.java:54)
        at org.apache.flink.runtime.operators.shipping.OutputCollector.collect(OutputCollector.java:65)
        at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35)
        at org.apache.flink.runtime.operators.chaining.ChainedMapDriver.collect(ChainedMapDriver.java:78)
        at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35)
        at org.apache.flink.api.java.operators.translation.PlanFilterOperator$FlatMapFilter.flatMap(PlanFilterOperator.java:58)
        at org.apache.flink.runtime.operators.chaining.ChainedFlatMapDriver.collect(ChainedFlatMapDriver.java:79)
        at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35)
        at org.apache.flink.api.java.operators.translation.PlanFilterOperator$FlatMapFilter.flatMap(PlanFilterOperator.java:58)
        at org.apache.flink.runtime.operators.chaining.ChainedFlatMapDriver.collect(ChainedFlatMapDriver.java:79)
        at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35)
        at org.apache.flink.runtime.operators.DataSourceTask.invoke(DataSourceTask.java:208)
        at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
        at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937)
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does not "opens java.util" to unnamed module @5b367418
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.buildValidFields(FieldSerializer.java:282)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.rebuildCachedFields(FieldSerializer.java:219)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.rebuildCachedFields(FieldSerializer.java:156)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:133)
        at org.apache.flink.runtime.types.ScalaCollectionsRegistrar.useField$1(FlinkScalaKryoInstantiator.scala:93)
        at org.apache.flink.runtime.types.ScalaCollectionsRegistrar.apply(FlinkScalaKryoInstantiator.scala:98)
        at org.apache.flink.runtime.types.AllScalaRegistrar.apply(FlinkScalaKryoInstantiator.scala:172)
        at org.apache.flink.runtime.types.FlinkScalaKryoInstantiator.newKryo(FlinkScalaKryoInstantiator.scala:84)
        ... 29 more`

- `12:21:08,050 ERROR org.apache.flink.runtime.operators.BatchTask                  - Error in task code:  CHAIN Join (Join child and parent.) -> Map (Map at io.rml.framework.Main$$anonfun$18.apply(Main.scala:692)) -> Map (Execute mapping statements on joined items) -> Map (Ignoring the logical target for now.) -> FlatMap (Convert triples to strings) (6/8)
java.lang.Exception: The data preparation for task 'CHAIN Join (Join child and parent.) -> Map (Map at io.rml.framework.Main$$anonfun$18.apply(Main.scala:692)) -> Map (Execute mapping statements on joined items) -> Map (Ignoring the logical target for now.) -> FlatMap (Convert triples to strings)' , caused an error: java.io.IOException: I/O channel already closed. Could not fulfill: org.apache.flink.runtime.io.disk.iomanager.SegmentWriteRequest@b14055
        at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:492)
        at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:360)
        at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
        at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937)
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.esotericsoftware.kryo.KryoException: java.io.IOException: I/O channel already closed. Could not fulfill: org.apache.flink.runtime.io.disk.iomanager.SegmentWriteRequest@b14055
        at com.esotericsoftware.kryo.io.Output.flush(Output.java:165)
        at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:317)
        at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.serialize(TupleSerializer.java:140)
        at org.apache.flink.api.java.typeutils.runtime.TupleSerializer.serialize(TupleSerializer.java:37)
        at org.apache.flink.runtime.operators.hash.HashPartition.insertIntoBuildBuffer(HashPartition.java:284)
        at org.apache.flink.runtime.operators.hash.MutableHashTable.insertIntoTable(MutableHashTable.java:1057)
        at org.apache.flink.runtime.operators.hash.MutableHashTable.buildInitialTable(MutableHashTable.java:838)
        at org.apache.flink.runtime.operators.hash.MutableHashTable.open(MutableHashTable.java:479)
        at org.apache.flink.runtime.operators.hash.NonReusingBuildFirstHashJoinIterator.open(NonReusingBuildFirstHashJoinIterator.java:110)
        at org.apache.flink.runtime.operators.JoinDriver.prepare(JoinDriver.java:270)
        at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:484)
        ... 6 more
Caused by: java.io.IOException: I/O channel already closed. Could not fulfill: org.apache.flink.runtime.io.disk.iomanager.SegmentWriteRequest@b14055
        at org.apache.flink.runtime.io.disk.iomanager.AsynchronousFileIOChannel.addRequest(AsynchronousFileIOChannel.java:256)
        at org.apache.flink.runtime.io.disk.iomanager.AsynchronousBlockWriterWithCallback.writeBlock(AsynchronousBlockWriterWithCallback.java:60)
        at org.apache.flink.runtime.io.disk.iomanager.AsynchronousBlockWriterWithCallback.writeBlock(AsynchronousBlockWriterWithCallback.java:29)
        at org.apache.flink.runtime.operators.hash.HashPartition$BuildSideBuffer.nextSegment(HashPartition.java:569)
        at org.apache.flink.runtime.memory.AbstractPagedOutputView.advance(AbstractPagedOutputView.java:139)
        at org.apache.flink.runtime.memory.AbstractPagedOutputView.write(AbstractPagedOutputView.java:205)
        at org.apache.flink.api.java.typeutils.runtime.DataOutputViewStream.write(DataOutputViewStream.java:42)
        at com.esotericsoftware.kryo.io.Output.flush(Output.java:163)
        ... 16 more`

Thank you so much in advance for any help.

**Comment by ghsnd** [comment]
Hi,

I'll reply in-line...

>     1. When I have an output, the files do not have an extension.

Correct. RMLStreamer uses Flink's StreamingFileSink is used which gives no file name extensions by default.
 
>     2. The output folder always has 8 files (or 16 if I run in a server) , no matter how many TSV files are mapped in the RML file. I feel like I'm losing data.

The number of files correspond to the number of slots (~threads) used. The data should be spread across those files. If you need all data in one file you can just concatenate them (if the output is nquads).
If there's data loss, there is something wrong with the mappings or a bug in RMLStreamer; no data should be lost.

>     3. When running, there is usually a neverending stream of errors, some of which appear as follows:

>     * `12:14:12,332 WARN  io.rml.framework.core.item.csv.CSVItem$                       - Cannot find reference: 'GRCH38-HG38-ENSEMBLv94'. Continuing with no value for this reference.` (this, I believe, is on my end. I was trying to have a constant TriplesMap that is not in any file, but was related to others, but have not found a way of doing so in the correct way);

Probably... This typically occurs when no column with name `GRCH38-HG38-ENSEMBLv94` can be found in the source TSV file.

>     * `12:15:02,916 WARN  org.apache.flink.metrics.MetricGroup                          - The operator name DataSource (at org.apache.flink.api.scala.ExecutionEnvironment.createInput(ExecutionEnvironment.scala:360) (io.rml.framework.flink.source.CSVInputFormat)) exceeded the 80 characters length limit and was truncated.`;

This can safely be ignored. Though we didn't find a way yet to suppress this warning.

>     * `12:15:03,512 WARN  org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer  - Falling back to default Kryo serializer because Chill serializer couldn't be found....

This can also be ignored. It means that somewhere some object cannot be (de)serialized optimally.
 
>     * `12:21:08,050 ERROR org.apache.flink.runtime.operators.BatchTask                  - Error in task code:  CHAIN Join (Join child and parent.) ...

Now this is something that might be an issue. Could you check if the output is complete?
If not, would it be possible to share (a sample of) data and mappings?

**Comment by PRAE399** [comment]
Hello, 

Thank you so much for the clarifications!
The last part usually happens when I run it on my computer, and the output is incomplete.
I believe it might be due to the size of the files; I did not notice it happen when I ran on the server... but I'll leave a snippet of the data and mapping rules below, just in case. I am following the same "rationale" for all the files.
[file1.txt](https://github.com/RMLio/RMLStreamer/files/10142148/file1.txt)
[file2.txt](https://github.com/RMLio/RMLStreamer/files/10142149/file2.txt)
[MappingsFile](https://drive.google.com/file/d/1T2NrKhayAG5DxQHHpoNEhFGLFxJy6WhP/view?usp=share_link)

Thank you once again for the help.

**Comment by s-minoo** [comment]
Hi, 

Using the sample input you provided, I ran the standalone RMLStreamer with Java11 and it produced  
26 triples in total in the following files: 
[1.txt](https://github.com/RMLio/RMLStreamer/files/10360016/1.txt)
[3.txt](https://github.com/RMLio/RMLStreamer/files/10360017/3.txt)
[4.txt](https://github.com/RMLio/RMLStreamer/files/10360018/4.txt)
[7.txt](https://github.com/RMLio/RMLStreamer/files/10360019/7.txt)

Do those match the expected output?

**Comment by s-minoo** [comment]
Ah! Looking closely at the error output, I see that it is caused by 
![image](https://user-images.githubusercontent.com/13002966/211011443-eb6df39c-d79c-4f34-8e3f-3f0f13a43ae2.png)

Can it be that whatever serializer/sink you used to write out the results is being closed before RMLStreamer actually finishes everything?

**Comment by PRAE399** [comment]
Yes, they look correct... could it be something to do with flink? 
Right now I am just running the tool as is. I have tried the instructions in the README file, but always had errors anyway... is there anything else I could do?

Thank you once again!

**Comment by s-minoo** [comment]
Have you checked which java version you're using to run? I have Java11 when I ran the sample

**Comment by PRAE399** [comment]
Yeah, I'm also using Java11. 
I'm running RMLStreamer again, I'll edit this comment with the warnings and errors that appear.
The first one is this:
![image](https://user-images.githubusercontent.com/63848877/211294251-ec937853-b353-46d7-a236-9429f6076dba.png)

**Comment by s-minoo** [comment]
Are there any triples generated in the output folder ?

**Comment by PRAE399** [comment]
Usually there is, but right now the output folder is empty. Since I have so much data, I never know when the tool has finished running.

**Comment by s-minoo** [comment]
Ah if the triples are generated then indeed the streamer is running well. If I may ask how many joins are there in the mapping rules? That takes a substantial amount of processing power out of the streamer. How big is the dataset (rough number) if I may ask?

**Comment by PRAE399** [comment]
I was still running the tool right now and there was a final group of errors like this:
![image](https://user-images.githubusercontent.com/63848877/211344728-5ef31c9a-b85a-4765-ae27-6e964891f849.png)

But I will do as you suggested now, thank you.
I will be back with updates!

**Comment by s-minoo** [comment]
Yup! Seems like RMLStreamer is running as expected. The error is there because there's no more space on your SSD/HDD.

**Comment by PRAE399** [comment]
I will now try out what you suggested, but to answer your questions: I have roughly 40 joinCondition in my mapping rules file. The mapping rules are to accommodate ten large TSV files (ranging from 1MB to 2GB), some with hundreds of thousands of rows and others with over a million.

**Comment by PRAE399** [comment]
I was running an updated version of the mapping rules, this is what happens:
![image](https://user-images.githubusercontent.com/63848877/211567858-7e029750-217d-4061-b5dd-479b8bc68755.png)
![image](https://user-images.githubusercontent.com/63848877/211568090-242bafad-77ba-410a-8615-f6d05e7418d4.png)
![image](https://user-images.githubusercontent.com/63848877/211568293-166c3409-15bf-436e-8565-76f173a13d7b.png)
![image](https://user-images.githubusercontent.com/63848877/211568388-b97e264e-065e-48f3-a5ab-f0dc0b3377f5.png)
![image](https://user-images.githubusercontent.com/63848877/211568450-6cf909ac-59bb-4d4a-bc46-fa29e53db63a.png)

**Comment by s-minoo** [comment]
Error for `EOF reached before encapsulated token finished` means that some of the rows in the dataset doesn't have the correct number of columns (assuming they're CSV-like).

**Comment by PRAE399** [comment]
Hello! I have tested the mapping rules for each file without the Predicate Object Map and aside from that EOF error it ran well. Now I'm trying with the Predicate Object Map and I'm having the following WARNS:
![image](https://user-images.githubusercontent.com/63848877/212335950-c6c36d49-5149-4ff9-98f5-d3c4cd97157b.png)
Since these are not error messages, I was wondering if they are critical and reflect in some way on the output?

**Comment by s-minoo** [comment]
I believe the  latest warnings could be solved if you start a separate Flink Job/Task managers and configure them to have a bigger buffer size.  I hope it has been of help to you.

**Comment by PRAE399** [comment]
Hello! I tried running the other version of RMLStreamer, and there is this error:
![image](https://user-images.githubusercontent.com/63848877/213522261-33fdeafa-cf47-460e-a8d3-cd7e4115d895.png)
I have also tried the previous version. Maybe there is something that I am missing while running this version?
I am using the same command I was using for the standalone version.
Thanks!

**Comment by s-minoo** [comment]
To use the normal version, you need a **flink cluster up and running** and **submit the jar file as a job to the flink cluster**. I think you could keep using the standalone verison since it is already generating outputs. 

The first error about not finding the **reference "peptide"** means that the column name **"peptide" doesn't exist** in the input file.

The second error is about **not having enough disk space** on the machine to write the output. Check how much disk space is left on the machine and make some space for the streamer to generate output.

**Comment by s-minoo** [comment]
Is it okay to close this issue? @PRAE399

**Comment by PRAE399** [comment]
Yes, thank you so much!
