### ISSUE TITLE
Error while processing

### ISSUE THREAD

**Issue by titoarrabal** [RMLio/RMLStreamer#46]
Hi, im trying to convert RML to RDF. But when im trying to execute it, it gaves me this error:
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at io.rml.framework.Main$.main(Main.scala:124)
        at io.rml.framework.Main.main(Main.scala)

**Comment by titoarrabal** [comment]
This are the program parameters
java -jar rmlstreamer.jar toFile --mapping-file C:/Users/Usuario/Desktop/TFG/Mapping/ComunidadMadrid/Meteorologicos/map1.rml.ttl --output-path  prueba.nt
Its gaves me this error: 
![image](https://github.com/RMLio/RMLStreamer/assets/72153934/c16fc103-7355-42bf-83ac-b2456c0f6aa0)
![image](https://github.com/RMLio/RMLStreamer/assets/72153934/35cfe26e-0306-4d96-9c69-b53c2c6c57d1)

**Comment by ghsnd** [comment]
There is indeed an issue with relative paths that's not entirely fixed yet. In your case, it might help to add the "current directory" to the output path: `--output-path ./prueba.nt` or, if that doesn't work, the absolute directory.
