### ISSUE TITLE
d2rq:Database not supported as data source

### ISSUE THREAD

**Issue by MathiasVDA** [RMLio/RMLStreamer#52]
Hello

I'm trying to use RMLStreamer on a relational database but seem to be running into some issues. I have a very simple RML mapping file that just creates a subject with a constant predicateoject map. I read in the README that relational databases should be supported?

```
C:\Users\VBP8501\Git\Knowledge graph\rinf>docker run --rm -v "C:\Users\VBP8501\Git\Knowledge graph\rinf":/data rmlio/rmlstreamer toFile -m /data/src/tunnel2.rml.ttl -o /data/output/tunnel2.ttl
13:36:57,661 INFO  io.rml.framework.Main$                                        - Mapping file: /data/src/tunnel2.rml.ttl
Job name: RMLStreamer
Base IRI: /
Parallelise over local task slots: true
Post processor: None
Checkpoint interval: /
Auto Watermark interval: 50
Output method: File
Output file: /data/output/tunnel2.ttl
Kafka broker list: /
Kafka topic: /
Kafka topic partition id: /
Output TCP socket: /
Function description locations: None
Discard output: false
13:36:58,180 WARN  io.rml.framework.core.model.rdf.jena.JenaResource             - Multiple rdf:types defined for resource.
io.rml.framework.shared.RMLException: http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#Database not supported as data source.
        at io.rml.framework.core.extractors.std.StdDataSourceExtractor.extractDataSourceFromResource(StdDataSourceExtractor.scala:75)
        at io.rml.framework.core.extractors.std.StdDataSourceExtractor.extract(StdDataSourceExtractor.scala:53)
        at io.rml.framework.core.extractors.std.StdDataSourceExtractor.extract(StdDataSourceExtractor.scala:36)
        at io.rml.framework.core.extractors.std.StdLogicalSourceExtractor.extractDataSource(StdLogicalSourceExtractor.scala:110)
        at io.rml.framework.core.extractors.std.StdLogicalSourceExtractor.extractLogicalSourceProperties(StdLogicalSourceExtractor.scala:76)
        at io.rml.framework.core.extractors.std.StdLogicalSourceExtractor.extract(StdLogicalSourceExtractor.scala:61)
        at io.rml.framework.core.extractors.std.StdLogicalSourceExtractor.extract(StdLogicalSourceExtractor.scala:39)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$.extractTriplesMapProperties(StdTriplesMapExtractor.scala:122)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$$anonfun$extract$1.apply(StdTriplesMapExtractor.scala:82)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$$anonfun$extract$1.apply(StdTriplesMapExtractor.scala:82)
        at scala.collection.immutable.List.flatMap(List.scala:338)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$.extract(StdTriplesMapExtractor.scala:81)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$.extract(StdTriplesMapExtractor.scala:38)
        at io.rml.framework.core.extractors.std.StdMappingExtractor.extract(StdMappingExtractor.scala:46)
        at io.rml.framework.core.extractors.std.StdMappingExtractor.extract(StdMappingExtractor.scala:36)
        at io.rml.framework.core.extractors.std.StdMappingReader.read(StdMappingReader.scala:52)
        at io.rml.framework.core.util.Util$.readMappingFile(Util.scala:206)
        at io.rml.framework.Main$.main(Main.scala:95)
        at io.rml.framework.Main.main(Main.scala)
13:36:58,197 WARN  io.rml.framework.core.extractors.std.StdTriplesMapExtractor$  - http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#Database not supported as data source.
13:36:58,198 WARN  io.rml.framework.core.extractors.std.StdTriplesMapExtractor$  - https://data.infrabel.be/mapping/rinf/OperationalPoint/1: Skipping triples map.
Exception in thread "main" io.rml.framework.shared.RMLException: http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#Database not supported as data source.
        at io.rml.framework.core.extractors.std.StdDataSourceExtractor.extractDataSourceFromResource(StdDataSourceExtractor.scala:75)
        at io.rml.framework.core.extractors.std.StdDataSourceExtractor.extract(StdDataSourceExtractor.scala:53)
        at io.rml.framework.core.extractors.std.StdDataSourceExtractor.extract(StdDataSourceExtractor.scala:36)
        at io.rml.framework.core.extractors.std.StdLogicalSourceExtractor.extractDataSource(StdLogicalSourceExtractor.scala:110)
        at io.rml.framework.core.extractors.std.StdLogicalSourceExtractor.extractLogicalSourceProperties(StdLogicalSourceExtractor.scala:76)
        at io.rml.framework.core.extractors.std.StdLogicalSourceExtractor.extract(StdLogicalSourceExtractor.scala:61)
        at io.rml.framework.core.extractors.std.StdLogicalSourceExtractor.extract(StdLogicalSourceExtractor.scala:39)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$.extractTriplesMapProperties(StdTriplesMapExtractor.scala:122)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$$anonfun$extract$1.apply(StdTriplesMapExtractor.scala:82)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$$anonfun$extract$1.apply(StdTriplesMapExtractor.scala:82)
        at scala.collection.immutable.List.flatMap(List.scala:338)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$.extract(StdTriplesMapExtractor.scala:81)
        at io.rml.framework.core.extractors.std.StdTriplesMapExtractor$.extract(StdTriplesMapExtractor.scala:38)
        at io.rml.framework.core.extractors.std.StdMappingExtractor.extract(StdMappingExtractor.scala:46)
        at io.rml.framework.core.extractors.std.StdMappingExtractor.extract(StdMappingExtractor.scala:36)
        at io.rml.framework.core.extractors.std.StdMappingReader.read(StdMappingReader.scala:52)
        at io.rml.framework.core.util.Util$.readMappingFile(Util.scala:206)
        at io.rml.framework.Main$.main(Main.scala:95)
        at io.rml.framework.Main.main(Main.scala)
```

**Comment by redmer** [comment]
I got this errror too, but then it turned out the latest Docker release was `RMLStreamer 2.1.0-SNAPSHOT`, whilst I see only in https://github.com/RMLio/RMLStreamer/releases/tag/v2.5.0 a reference to JDBC.
